config/routes.rb
Rails.application.routes.draw do  
  root "welcome#index"

  devise_for :users, :controllers => {
    registrations: "registrations"
  }

  resources :users

  resources :contacts

  resources :tasks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  has_many :contacts

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "contact successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to root_path, notice: "contact successfully updated." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.save

    respond_to do |format|
      format.html { redirect_to contacts_path, notice: "contact successfully deleted." }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:company_name, :company_background, :company_address, :phone).merge(user_id: current_user.id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def sign_up_params
      params.require(:user).permit(:email, :first_name, :last_name, :job_title, :company, :password, :password_confirmation).merge(role_id: 1)
    end

    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :job_title, :company, :current_password, :password, :password_confirmation) 
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: "task created successfully." }
      else
        format.html { render :new, notice: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "task updated successfully." }
      else
        format.html { render :edit, notice: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "task deleted successfuly." }
    end
  end

  private
    def task_params
      params.require(:task).permit(:content, :description, :is_complete).merge(user_id: current_user.id)
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        form.html { redirect_to root_path, notice: "user created successfully." }
      else
        format.html { render :new, notice: "user could not be created.", status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "user updated successfully." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: "user deleted successfully." }
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :job_title, :company, :password, :password_confirmation).merge(role_id: 2)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contacts = current_user.contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: @contact do |form| %>
  <div class="mb-3">
    <%= form.label :company_name, class: "form-label" %>
    <%= form.text_field :company_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :company_background, class: "form-label" %>
    <%= form.text_field :company_background, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :company_address, class: "form-label" %>
    <%= form.text_field :company_address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Add contact", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<section class="model-form">
  <h1>Add new contact</h1>
  <section class="white-bg">
    <%= render "form", controller: @contact %>
  </section>
</section>

app/views/contacts/show.html.erb
<section class="company-details">
  <h1>Company Details</h1>
  <section class="single-contact">
    <h4><%= @contact.company_name.titleize %></h4>
    <p><%= @contact.company_background.capitalize %></p>
    <b><%= @contact.phone %></b>
  </section>
</section>

app/views/layouts/_alerts.html.erb
<section class="alerts-section">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deeler: Easy deals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('deeler-favicon.png') %>
  </head>

  <body>
    <% if current_user %>
      <div class="main-body">
        <%= render "shared/logged_in_navbar" %>
        <div class="main-content">
          <%= render "shared/search_form" %>
          <%= render "layouts/alerts" %>
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/shared/_contacts.html.erb
<% if @contacts.size > 0 %>
  <h1>Your contacts</h1>
  <% @contacts.each do |contact| %>
    <section class="single-contact">
      <h3><%= link_to contact.company_name.titleize, contact %></h3>
      <p><%= contact.company_background.capitalize %></p>
    </section>
  <% end %>
  <section class="new-btn">
    <%= link_to "Add new contact", new_contact_path, class: "btn btn-primary" %>
  </section>
  <% else %>
    <h3>No contacts at the moment</h3>
    <section class="new-btn">
      <%= link_to "Add new contact", new_contact_path, class: "btn btn-primary" %>
  </section>
<% end %>

app/views/shared/_logged_in_navbar.html.erb
<% if current_user %>
  <section class="side-navbar">
    <section class="nav-brand">
      <a href="/"><%= image_tag "deeler.png" %></a>
    </section>
    <hr>
    <section class="user-profile">
      <%= image_tag "avataaars.png" %>
      <section class="user-details">
        <%= current_user.first_name + " " + current_user.last_name %>
        <small class="light-grey"><%= current_user.email %></small>
      </section>
    </section>
    <section class="nav-links">
      <ul class="dashboard-link">
          <li><i class="bi bi-sliders"></i></li>
          <li><%= link_to "Dashboard", root_path %></li>
        </ul>
      <ul class="dashboard-link">
        <li><i class="bi bi-diagram-2"></i></li>
        <li><%= link_to "Tasks", tasks_path %></li>
      </ul>
      <ul class="dashboard-link">
        <li><i class="bi bi-person"></i></li>
        <li><%= link_to "Contacts", contacts_path %></li>
      </ul>
      <ul class="dashboard-link">
        <li><i class="bi bi-chat"></i></li>
        <li><%= link_to "Follow up" %></li>
      </ul>
      <ul class="dashboard-link">
        <li><i class="bi bi-filter-square"></i></li>
        <li><%= link_to "Deals" %></li>
      </ul>
    </section>
    <hr>

    <ul class="dashboard-link">
        <li><i class="bi bi-box-arrow-in-right"></i></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </section>
<% end %>

app/views/shared/_search_form.html.erb
<section class="search-form">
  <%= form_with model: Contact.new do |form| %>
    <%= form.text_field :company_background, class: "form-control me-2", placeholder: "search here..." %>
  <% end %>
</section>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_field :content, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <%= form.label "Task status", class: "form-label" %>
  <div class="form-check">
    <%= form.radio_button :is_complete, "false", class: "form-check-input" %>
    <%= form.label "Pending", class: "form-check-label" %>
  </div>

  <div class="form-check">
    <%= form.radio_button :is_complete, "true", class: "form-check-input" %>
    <%= form.label "Done", class: "form-check-label" %>
  </div>

  <div class="vertical-divide"></div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<section class="white-bg">
  <%= render "form", task: @task %>
</section>

app/views/tasks/index.html.erb
<% if @tasks.size > 0 %>
  <h1>Tasks</h1>
  <section class="all-tasks">    
    <% @tasks.each do |task| %>
      <section class="single-task">
        <%= link_to task.content.capitalize, edit_task_path(task) %><br>
        <small class="light-grey"><%= task.is_complete ? "Done" : "Pending" %></small>
      </section>
    <% end %>
  </section>
  <div class="vertical-divide"></div>
  <%= link_to "Add new task", new_task_path, class: "btn btn-primary" %>
<% else %>
  <h1>You do not have any tasks.</h1><br> 
  <%= link_to "Add new task", new_task_path, class: "btn btn-primary" %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<section class="task-form white-bg">
  <%= render "form", task: @task %>
</section>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<section class="user-dashboard">
  <section class="activity-summary">
    <h1>User summary</h1>
  </section>
  <section class="user-deals-tasks">
    <section class="user-deals">
      <section class="top-bar">
        <h4>Deals</h4>
        <span>Show: Monthly</span>
      </section>
      <hr>
    </section>
    <div class="vertical-divide"></div>
    <section class="user-tasks">
      <section class="top-bar">
        <h4>Tasks</h4>
        <span>Show: This Month</span>
      </section>
      <hr>
    </section>
  </section>
</section>